blog/urls.py
from django.urls import path, re_path

from .views import TodasPublicacoes, Ver_publicacao, Categorias, ArtigosCategoria

urlpatterns = [
    path('', TodasPublicacoes.as_view(), name='index'),
    path('categorias/', Categorias.as_view(), name='categorias'),
    path('categorias/<int:pk>/', ArtigosCategoria.as_view(), name='artigos-por-categoria'),
    path('<slug:slug>/', Ver_publicacao, name='ver-publicacao' ),
]

# path('<slug:pagina>/', Subscrever.as_view(), name='subscrever')
# re_path(r"^subscrever/(?P<pagina>[./a-zA-Z]+)/$", Subscrever.as_view(), name='subscrever')
# r"^(subscrever?P<pagina>[-a-zA-Z]+)/$"

noite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    # path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from random import randint as rdi


# Create your models here.

CONDICAO = (
    (0, "Rascunho"),
    (1, "Publicar")
)


class Categoria(models.Model):
    publicacoes = models.ForeignKey(
        "blog.publicacao",
        on_delete=models.CASCADE,
        related_name='publicacoes'
    )
    nome = models.CharField(max_length=100, unique=True)
    descricao = models.TextField()

    def pequena_descricao(self):
        return " ".join(self.descricao.split()[:5])

    def __str__(self):
        return self.nome


class Publicacao(models.Model):
    autor = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='publicacoes'
    )

    tag = models.ManyToManyField(
        'blog.Tag',
        related_name='publicacoes'
    )

    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=200, unique=True)
    titulo = models.CharField(max_length=200, unique=True)
    conteudo = models.TextField()
    condicao = models.IntegerField('Condição', choices=CONDICAO, default=0)
    criado_em = models.DateTimeField('Data de criação', auto_now_add=True)
    modificado_em = models.DateTimeField('Ultima alteração', auto_now=True)

    def _comentarios(self):
        return self.comentarios.count()

    def get_tags(self):
        return list(self.tag.all())

    class Meta:
        ordering = ['-criado_em']

    def __str__(self):
        return self.titulo


class Tag(models.Model):
    # Publicacao = models.ManyToManyField("blog.publicacao", related_name="publicacao")
    nome = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nome


class Comentario(models.Model):
    publicacao = models.ForeignKey(
        "blog.publicacao",
        on_delete=models.CASCADE,
        related_name='comentarios'
    )

    nome = models.CharField(max_length=80)
    email = models.EmailField()
    conteudo = models.TextField()
    criado_em = models.DateTimeField(auto_now_add=True)
    activo = models.BooleanField(default=False)

    class Meta:
        ordering = ['criado_em']

    def __str__(self):
        return f'Comentário de {self.nome}: {self.conteudo}'


class ViwerEmail(models.Model):
    email = models.EmailField()
    criado_em = models.DateTimeField('Data de criação', auto_now_add=True)
    notificado = models.BooleanField(default=False)

blog/forms.py
from django import forms
from .models import Comentario, ViwerEmail
from django.utils.translation import gettext_lazy as _


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('nome', 'email', 'conteudo')

        labels = {
            'conteudo': _('Comentario'),
            'email': _('E-mail'),
        }


class SubscreverForm(forms.ModelForm):
    class Meta:
        model = ViwerEmail
        fields = ('email',)
        labels = {
            'email': _('E-mail'),
        }

blog/views.py
from django.views.generic.edit import FormMixin
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Publicacao, Categoria
from .forms import ComentarioForm, SubscreverForm


# Create your views here.
class TodasPublicacoes(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'publicacoes'
    queryset = Publicacao.objects.filter(condicao=1).order_by('-criado_em')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()
        context['subscrever_form'] = SubscreverForm()
        return context

    def post(self, request, *args, **kwargs):
        form = SubscreverForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')


class Categorias(ListView):
    template_name = 'blog/categorias.html'
    context_object_name = 'categorias'
    model = Categoria

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['publicacoes'] = Publicacao.objects.filter(condicao=1).order_by('-criado_em')
        context['subscrever_form'] = SubscreverForm()
        return context

    def post(self, request, *args, **kwargs):
        form = SubscreverForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/categorias')


class ArtigosCategoria(FormMixin, DetailView):
    template_name = 'blog/artigos_por_categoria.html'
    context_object_name = 'categoria'
    model = Categoria
    form_class = SubscreverForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['publicacoes'] = get_list_or_404(Publicacao, categoria=context['categoria'])
        context['categorias'] = Categoria.objects.all()
        context['subscrever_form'] = SubscreverForm()
        return context

    def get_success_url(self):
        return reverse('artigos-por-categoria', kwargs={'pk': self.object.pk})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        self.form_valid(form) if form.is_valid() else self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def Ver_publicacao(request, slug):
    template_name = 'blog/ver_publicacao.html'
    publicacao = get_object_or_404(Publicacao, slug=slug)

    publicacoes = Publicacao.objects.filter(
        condicao=1,
        categoria=publicacao.categoria
    ).order_by('-criado_em')[:5]

    categorias = Categoria.objects.all()

    comentarios = publicacao.comentarios.filter(activo=True)
    novo_comentario = None

    # Comentario postado
    if request.method == 'POST':
        comentario_form = ComentarioForm(data=request.POST)
        form = SubscreverForm(request.POST)
        if form.is_valid():
            form.save()

        if comentario_form.is_valid():

            novo_comentario = comentario_form.save(commit=False)
            novo_comentario.publicacao = publicacao
            novo_comentario.save()
    else:
        comentario_form = ComentarioForm()

    return render(request, template_name, {
        'publicacoes': publicacoes,
        'categorias': categorias,
        'publicacao': publicacao,
        'comentarios': comentarios,
        'novo_comentario': novo_comentario,
        'comentario_form': comentario_form,
        'subscrever_form': SubscreverForm(),
    })

blog/templates/blog/artigos_por_categoria.html
{% extends "base.html" %} {% load static %} {% block header %}

<header style="background-image:url('{% static 'images/header-background.jpg' %}');">
  {% include "navbar.html" %} {% block base_title %}

  <div class="center-align">
    <h1> {{ categoria }} </h1>
    <hr>
  </div>

  {% endblock base_title %}
</header>

{% endblock header %} {% block content %}
<div class="artigos">
  <div class="linha">

    {% for publicacao in publicacoes %}
    <div class="six colunas collapsed">
      <div class="artigo horizontal">

        <div class="artigo-header">
          <a href="{% url 'ver-publicacao' publicacao.slug  %}">
            <img src="{% static publicacao.imagem.name %}" alt="imagem da publicacao">
          </a>
        </div>

        <div class="conteudo">
          <div class="titulo">
            <h4>{{ publicacao.titulo|title|truncatechars:20 }}</h4>
            <small> {{ publicacao.autor.get_full_name }} </small>
          </div>
          <p>
            {{ publicacao.conteudo|safe|truncatewords:15 }}
          </p>
        </div>

      </div>
    </div>
    {% empty %}
    <h2>Sem pub...</h2>
    {% endfor %}

  </div>
</div>

{% endblock content %}

blog/templates/blog/categorias.html
{% extends "base.html" %} {% load static %} {% block header %}

<header style="background-image:url('{% static 'images/header-background.jpg' %}');">
  {% include "navbar.html" %} {% block base_title %}

    <div class="center-align">
      <h1> Artigos e as suas categorias</h1>
      <hr>
    </div>

  {% endblock base_title %}
</header>

{% endblock header %} {% block content %}

<div class="linha categorias">

    {% for categoria in categorias %}

      <div class="twelve colunas">

        <div class="categoria">
          <h2> {{ categoria.nome }} </h2>
          <p> {{ categoria.descricao }} </p>
        </div>

        <div class="artigos-bottom" style="padding:40px 20px 0px; margin-bottom:20px;">
          {% for publicacao in publicacoes  %}
            {% if publicacao.categoria == categoria %}
            
            <div class="colunas">
              <div class="artigo">
                <div class="artigo-header">
                  <a href="{% url 'ver-publicacao' publicacao.slug  %}">
                    <img src="{% static publicacao.imagem.name %}" alt="imagem da publicacao">
                  </a>
                  <div class="titulo">
                    <h4> {{ publicacao.titulo|title|truncatechars:25 }} </h4>
                    <small> {{ publicacao.autor.get_full_name }} /</small>
                    <small> {{ publicacao.categoria }} </small>
                  </div>
                </div>
              </div>
            </div>

            {% endif %}
          {% endfor %}

        </div>

          <a href="{% url 'artigos-por-categoria' categoria.id %}" class="btn-bordado">Ver mais</a>

      </div>

    {% endfor %}

</div>

{% endblock content %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="artigos" style="padding-bottom:0;">

  <div class="linha" style="padding-bottom:80px;">
    <div class="twelve colunas text-center" id="artgs">
      <h2>Esteja a par do que acontece a tua volta</h2>
      <h3>Artigos recentes</h3>
      <hr>
    </div>
  </div>

  <div class="linha fluida">
    <div class="eight colunas artigos-main">

      {% for post in publicacoes|slice:5 %}

        {% if forloop.counter == 3 %}

          <div class="twelve colunas">
            <div class="artigo">

              <div class="artigo-header">
                <a href="{% url 'ver-publicacao' post.slug  %}">
                  <img src="{% static post.imagem.name %}" alt="imagem da publicacao">
                </a>
              </div>

              <div class="conteudo">
                <h4> {{ post.titulo|title }} </h4>
                <p>
                  {{ post.conteudo|safe|truncatewords:40 }}
                </p>
              </div>

              <div class="time">
                <i class="fa fa-clock-o"></i>
                <span>{{ post.criado_em|timesince }} atrás</span>
              </div>

              <hr>

              <div class="autor">
                <img src=" {% static 'img/leyni.png' %} " alt="mia">
                <h4> {{ post.autor.get_full_name }} </h4>
              </div>
              
            </div>
          </div>

        {% else %}

          <div class="six colunas">
            <div class="artigo">

              <div class="artigo-header">
                <a href="{% url 'ver-publicacao' post.slug  %}">
                  <img src="{% static post.imagem.name %}" alt="imagem da publicacao">
                </a>
              </div>

              <div class="conteudo">
                <h4> {{ post.titulo|title }} </h4>
                <p>
                  {{ post.conteudo|safe|truncatewords:"19" }}
                </p>
              </div>

              <div class="time">
                <i class="fa fa-clock-o"></i>
                <span>{{ post.criado_em|timesince}} atrás</span>
              </div>

              <hr>

              <div class="autor">
                <img src=" {% static 'img/leyni.png' %} " alt="mia">
                <h4>{{ post.autor.get_full_name }}</h4>
              </div>

            </div>
          </div>
        {% endif %}

      {% empty %}
      <h2>Sem publicacoes por enquanto.</h2>
      {% endfor %}

    </div>

    <div class="four colunas artigos-side">

      {% for post in publicacoes|slice:5 %}

      <div class="twelve colunas">
        <div class="artigo">

          <div class="artigo-header">
            <a href="{% url 'ver-publicacao' post.slug  %}">
              <img src="{% static post.imagem.name %}" alt="imagem da publicacao">
            </a>
          </div>

          <div class="titulo">
            <h4 style="margin-bottom:5px;"> {{ post.titulo|title }} </h4>
            <small> {{ post.autor.get_full_name }} / {{ post.categoria }} </small>
          </div>
          
        </div>
      </div>

      {% empty %}
      <h2>Sem publicacoes por enquanto.</h2>
      {% endfor %}
      
    </div>
  </div>
</div>

{% endblock content %}

blog/templates/blog/ver_publicacao.html
{% extends "base.html" %}
{% load static %}

{% block css_js %}
  {{ block.super }}
  <script type="text/javascript" src="{% static 'syntaxhighlighter/scripts/shCore.js'%}"></script>
  <script type="text/javascript" src="{% static 'syntaxhighlighter/scripts/shBrushPython.js'%}"></script>
  <script type="text/javascript">SyntaxHighlighter.all();</script>
{% endblock css_js %}

{% block header %}

<header style="background-image:url('{% static publicacao.imagem.name %}');">

  {% include "navbar.html" %}
  <div id="big-title">
    <h1 class="activador">{{ publicacao.titulo|title }} <hr> </h1>
  </div>

</header>

{% endblock header %}

{% block content %}

<div class="linha">
  <div class="blog twelve coluna">
    <div class="texto">
      <div class="publicacao-conteudo">
        {{ publicacao.conteudo|safe }}
      </div>

      <div class="tags">

        {% for tag in publicacao.get_tags %}
        
          <a class="tag" href="#"> {{ tag }} </a>

        {% endfor %}
      </div>

      <div class="time" style="text-align:right;">
        <i class="fa fa-calendar"></i>
        <span> {{ publicacao.criado_em|date }} </span>
      </div>

      <hr>

      <div class="autor">
        <img src=" {% static 'img/leyni.png' %} " alt="leynilson">
        <h4> {{ publicacao.autor.get_full_name }} </h4>
      </div>

    </div>
  </div>
</div>

<div class="linha total">
  <div class="twelve colunas artigos-bottom">

    {% for publicacao in publicacoes  %}

    <div class=" colunas">
      <div class="artigo">
        <div class="artigo-header">
          <a href="{% url 'ver-publicacao' publicacao.slug  %}">
            <img src="{% static publicacao.imagem.name %}" alt="imagem da publicacao">
          </a>
          <div class="titulo">
            <h4>{{ publicacao.titulo|title|truncatechars:25 }}</h4>
            <small> {{ publicacao.autor.get_full_name }} </small>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}

  </div>
</div>

<div class="comentario">
  <div class="linha">
    <div class="twelve coluna">
      <div class="texto">

        {% if novo_comentario %}
        <div class="text-center">
          <h2> O seu comentario será posto em avaliação </h2>
          <h2> {{  novo_comentario.activo }} </h2>
        </div>
        {% else %}
        
        <div class="text-center">
          <h2>O que achaste deste artigo?</h2>
          <h3>Deixa o teu comentário</h3>
        </div>

        <form method="post">
          <div class="comentario_form">
            {{ comentario_form }}
            {% csrf_token %}
          </div>
          <input class="btn-bordado smt" type="submit" value="Comentar">
        </form>

        {% endif %}
        
        <div class="comentarios">

          {% for comentario in comentarios %}

          <div class="user">
            <img src=" {% static 'img/leyni.png' %} " alt="mia">
            <div class="comment">
              <div class="autor" id="id_autor">
                <h4> {{ comentario.nome }} </h4>
                <div class="time">
                  <i class="fa fa-clock-o"></i>
                  <span>{{ comentario.criado_em|timesince }} atrás</span>
                </div>
                
              </div>
              <p> {{ comentario.conteudo }} </p>
            </div>
          </div>

          {% empty %}

          <h2>Sem Comentários</h2>

          {% endfor %}

          </div>

        </div>
      </div>
    </div>
  </div>

  {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block css_js %}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/blog.css' %}">
    <script src=" {% static 'jquery-3.3.1.js' %} "></script>
    <script src=" {% static 'main.js' %} "></script>
  {% endblock css_js %}

  <title>Meu Blog</title>
</head>

<body>


  {% block header %}

    <header style="background-image:url( {% static 'img/wh3.jpg' %} );">

      {% include "navbar.html" %} {% block base_title %}

        <div class="center-align">
          <h1 class="activador">Fique a par de tudo que esta a acontecer no mundo, aqui e em primeira mão.</h1>
          <div class="btn-group">
            <a href="#" class="btn-bordado activo">Ver Agora</a>
            <a href="#" class="btn-bordado">Ver Mais</a>
          </div>
        </div>

        {% endblock base_title %}


    </header>
  {% endblock header %} {% block content %}
    <!-- ------------------
      Conteudo das páginas
    <!-> ------------ <@-->
  {% endblock content %}

  <div class="subscrever" id="subs">
    <div class="linha">
      <div class="twelve coluna">
        <div class="texto">

          <div class="text-center">
            <h2>Se Inscvreva</h2>
            <h3>Inscreva-se no nosso boletim de notícias</h3>
            <form method="post">
              <div class="subscrever-form">
                {% csrf_token %}
                {{ subscrever_form }}
              </div>
              <input class="btn-bordado smt" type="submit" value="Subscrever">
            </form>
          </div>

        </div>
      </div>
    </div>
  </div>

  <footer>
    <div class="linha">
      <div class="two coluna nt">
        <a class="logo" href="#">Noite.</a>
      </div>
      <div class="eight coluna links">
        {% for categoria in categorias %}
          <a href="{% url 'artigos-por-categoria' categoria.id %}" class="link">{{ categoria.nome }}</a>
        {% endfor %}
      </div>
      <div class="two coluna icones">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-instagram"></i></a>
        <a class="activo" href="#"><i class="fa fa-arrow-up"></i></a>
      </div>
    </div>
  </footer>
</body>

</html>

templates/navbar.html
{% block navbar %}

<nav>
  <div id="nav-wrapper">

    <ul>
      <li>
        <a class="logo" href="{% url 'index' %}">Noite.</a>
      </li>
    </ul>

    <ul class="nav-direita">
      <li>
        <a class="link" href="#">Sobre</a>
      </li>

      <li class="dropdown-menu">

        <div class="dropdown-icon">
          <a href="{% url 'categorias' %}" class="link">
            Artigos
            <i class="fa fa-chevron-down"></i>
          </a>
        </div>

        <div class="dropdown-itens">
          {% for categoria in categorias %}
            <a href="{% url 'artigos-por-categoria' categoria.id %}" class="item"> {{ categoria.nome }} </a>
          {% endfor %}
        </div>

      </li>
      <li>
        <a class="btn-bordado" href="#subs">Subscrever</a>
      </li>
    </ul>

  </div>
</nav>
{% endblock navbar %}